package utilities;

/**
 *
 * @author Georgios
 */
public enum Tokenizer {
    CHARACTER_BIGRAMS,
    CHARACTER_BIGRAMS_MULTISET,
    CHARACTER_TRIGRAMS,
    CHARACTER_TRIGRAMS_MULTISET,
    CHARACTER_FOURGRAMS,
    CHARACTER_FOURGRAMS_MULTISET,
    CHARACTER_FIVEGRAMS,
    CHARACTER_FIVEGRAMS_MULTISET,
    WHITESPACE,
    WHITESPACE_MULTISET,
}
